use_frameworks!
platform :ios, '11.0'

target 'BringgDriverSDKExample' do
  # BringgDriverSDKObjc should be added to the podfile if you need Objc support
  pod 'BringgDriverSDKObjc', :path => '../'

  # The following line should be added to the podfile
  # It is a fork of Starscream that adds data usage tracking to the socket connection
  pod 'Starscream', :git => "https://github.com/bringg/Starscream", :branch => "feature/data_usage_feature_swift_5"
  
  # These pods are used for the example app. You do not have to add them to your podfile
  pod 'CocoaLumberjack/Swift', '3.6.0'
  pod 'PhoneNumberKit'
  pod 'FSPagerView'
  pod 'SnapKit'

  # All dependencies of the BringgDriverSDK needs to be built with the 'BUILD_LIBRARY_FOR_DISTRIBUTION' configuration set to 'YES'
  BringgDriverSDKDependencies = [
    'Socket.IO-Client-Swift',
    'Starscream',
    'libPhoneNumber-iOS',
    'CryptoSwift',
    'GzipSwift',
    'Alamofire',
    'XCGLogger',
    'RealmSwift',
    'ObjcExceptionBridging',
    'Kingfisher',
    'KeychainAccess',
    'DeviceKit'
    ]
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if BringgDriverSDKDependencies.include? target.name
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end
