// Generated by Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import CoreLocation;
@import CoreData;
@import SocketIO;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BringgDriverSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@protocol LoginManagerProtocol;
@protocol ShiftManagerProtocol;
@protocol TasksManagerProtocol;
@protocol LogReportsManagerProtocol;

SWIFT_CLASS("_TtC15BringgDriverSDK6Bringg")
@interface Bringg : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Bringg * _Null_unspecified shared;)
+ (Bringg * _Null_unspecified)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Bringg * _Null_unspecified)value;
@property (nonatomic, readonly, strong) id <LoginManagerProtocol> _Nonnull loginManager;
@property (nonatomic, readonly, strong) id <ShiftManagerProtocol> _Nonnull shiftManager;
@property (nonatomic, readonly, strong) id <TasksManagerProtocol> _Nonnull tasksManager;
@property (nonatomic, readonly, strong) id <LogReportsManagerProtocol> _Nonnull logReportManager;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@protocol LoggerProtocol;

@interface Bringg (SWIFT_EXTENSION(BringgDriverSDK))
+ (void)initializeSDKWithLogger:(id <LoggerProtocol> _Nullable)logger;
+ (void)initializeSDKWithHTTPBaseURL:(NSString * _Nonnull)httpBaseURL realtimeBaseURL:(NSString * _Nonnull)realtimeBaseURL logger:(id <LoggerProtocol> _Nullable)logger;
@end






SWIFT_CLASS("_TtC15BringgDriverSDK7Contact")
@interface Contact : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// Protocol to be conformed to by <code>NSManagedObject</code> subclasses that allow for convenience
/// methods that make fetching, inserting, deleting, and change management easier.
SWIFT_PROTOCOL("_TtP15BringgDriverSDK17CoreDataModelable_") SWIFT_AVAILABILITY(macos,introduced=10.10,deprecated=10.12,message="Use Xcode automatic generated subclass") SWIFT_AVAILABILITY(ios,introduced=8.0,deprecated=10.0,message="Use Xcode automatic generated subclass")
@protocol CoreDataModelable <NSFetchRequestResult>
/// The name of your <code>NSManagedObject</code>’s entity within the <code>XCDataModel</code>.
///
/// returns:
/// String: Entity’s name in <code>XCDataModel</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC15BringgDriverSDK8Customer")
@interface Customer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("GGContact")
@interface GGContact : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface GGContact (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end

@class GGWaypoint;

@interface GGContact (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable contactType;
@property (nonatomic, copy) NSString * _Nullable contactValue;
@property (nonatomic) int64_t customerId;
@property (nonatomic) BOOL sharingAllowed;
@property (nonatomic, strong) GGWaypoint * _Nullable waypoint;
@end


SWIFT_CLASS_NAMED("GGCustomer")
@interface GGCustomer : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface GGCustomer (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end

@class NSNumber;

@interface GGCustomer (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable addressSecondLine;
@property (nonatomic, strong) NSNumber * _Nullable allowSendingSMS;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) double lat;
@property (nonatomic) double lng;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) GGWaypoint * _Nullable waypointToWhichCustomerIsExtra;
@property (nonatomic, strong) GGWaypoint * _Nullable waypointToWhichCustomerIsPrimary;
@end


SWIFT_CLASS_NAMED("GGNote")
@interface GGNote : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface GGNote (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end

@class GGTask;

@interface GGNote (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic) int64_t customerId;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic) int64_t waypointId;
@property (nonatomic, strong) GGTask * _Nullable task;
@end


SWIFT_CLASS_NAMED("GGTask")
@interface GGTask : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface GGTask (SWIFT_EXTENSION(BringgDriverSDK))
- (void)addTaskNotesObject:(GGNote * _Nonnull)value;
- (void)removeTaskNotesObject:(GGNote * _Nonnull)value;
- (void)addTaskNotes:(NSSet * _Nonnull)values;
- (void)removeTaskNotes:(NSSet * _Nonnull)values;
@end


@interface GGTask (SWIFT_EXTENSION(BringgDriverSDK))
- (void)addWaypointsObject:(GGWaypoint * _Nonnull)value;
- (void)removeWaypointsObject:(GGWaypoint * _Nonnull)value;
- (void)addWaypoints:(NSSet * _Nonnull)values;
- (void)removeWaypoints:(NSSet * _Nonnull)values;
@end

@class GGTaskInventory;

@interface GGTask (SWIFT_EXTENSION(BringgDriverSDK))
- (void)addTaskInventoriesObject:(GGTaskInventory * _Nonnull)value;
- (void)removeTaskInventoriesObject:(GGTaskInventory * _Nonnull)value;
- (void)addTaskInventories:(NSSet * _Nonnull)values;
- (void)removeTaskInventories:(NSSet * _Nonnull)values;
@end


@interface GGTask (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


@interface GGTask (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, strong) NSNumber * _Nullable activeWayPointId;
@property (nonatomic, strong) NSNumber * _Nullable asap;
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic, copy) NSString * _Nullable groupUUID;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSDate * _Nullable lastAssignedTime;
@property (nonatomic, strong) NSNumber * _Nullable priority;
@property (nonatomic) int64_t runId;
@property (nonatomic, copy) NSDate * _Nullable scheduledAt;
@property (nonatomic, copy) NSDate * _Nullable startedTime;
@property (nonatomic, strong) NSNumber * _Nullable status;
@property (nonatomic, strong) NSNumber * _Nullable tagId;
@property (nonatomic, copy) NSString * _Nullable taskCancellationReason;
@property (nonatomic, copy) NSString * _Nullable taskConfigurationId;
@property (nonatomic, strong) NSNumber * _Nullable taskTypeId;
@property (nonatomic, strong) NSNumber * _Nullable tipDriverEnabled;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSSet * _Nullable taskInventories;
@property (nonatomic, strong) NSSet * _Nullable taskNotes;
@property (nonatomic, strong) NSSet * _Nullable waypoints;
@end


SWIFT_CLASS_NAMED("GGTaskInventory")
@interface GGTaskInventory : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface GGTaskInventory (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


@interface GGTaskInventory (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable externalId;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) int64_t inventoryId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int32_t originalQuantity;
@property (nonatomic) BOOL pending;
@property (nonatomic) double price;
@property (nonatomic) int32_t quantity;
@property (nonatomic, copy) NSString * _Nullable scanString;
@property (nonatomic) int64_t waypointId;
@property (nonatomic, strong) GGTask * _Nullable task;
@end


SWIFT_CLASS_NAMED("GGWaypoint")
@interface GGWaypoint : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface GGWaypoint (SWIFT_EXTENSION(BringgDriverSDK))
- (void)addContactsObject:(GGContact * _Nonnull)value;
- (void)removeContactsObject:(GGContact * _Nonnull)value;
- (void)addContacts:(NSSet * _Nonnull)values;
- (void)removeContacts:(NSSet * _Nonnull)values;
@end


@interface GGWaypoint (SWIFT_EXTENSION(BringgDriverSDK))
- (void)addExtraCustomersObject:(GGCustomer * _Nonnull)value;
- (void)removeExtraCustomersObject:(GGCustomer * _Nonnull)value;
- (void)addExtraCustomers:(NSSet * _Nonnull)values;
- (void)removeExtraCustomers:(NSSet * _Nonnull)values;
@end


@interface GGWaypoint (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


@interface GGWaypoint (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable addressSecondLine;
@property (nonatomic) BOOL allowEditingInventory;
@property (nonatomic, strong) NSNumber * _Nullable allowTargetQuantityEdit;
@property (nonatomic) BOOL asap;
@property (nonatomic) BOOL automaticCheckin;
@property (nonatomic) BOOL automaticCheckout;
@property (nonatomic, copy) NSString * _Nullable borough;
@property (nonatomic, copy) NSDate * _Nullable checkinTime;
@property (nonatomic, copy) NSDate * _Nullable checkoutTime;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable companyName;
@property (nonatomic, strong) NSNumber * _Nullable customerId;
@property (nonatomic, strong) NSNumber * _Nullable distance;
@property (nonatomic, copy) NSString * _Nullable district;
@property (nonatomic, strong) NSNumber * _Nullable done;
@property (nonatomic, strong) NSNumber * _Nullable editInventory;
@property (nonatomic, strong) NSNumber * _Nullable editPayment;
@property (nonatomic, copy) NSDate * _Nullable eta;
@property (nonatomic, copy) NSDate * _Nullable etl;
@property (nonatomic, strong) NSNumber * _Nullable findMe;
@property (nonatomic, copy) NSDate * _Nullable hasToLeaveBy;
@property (nonatomic, copy) NSString * _Nullable houseNumber;
@property (nonatomic) int64_t id;
@property (nonatomic, strong) NSNumber * _Nullable lat;
@property (nonatomic) BOOL late;
@property (nonatomic, strong) NSNumber * _Nullable lng;
@property (nonatomic) BOOL mustApproveInventory;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) NSNumber * _Nullable phoneAvailable;
@property (nonatomic, strong) NSNumber * _Nullable pickupDropoffOption;
@property (nonatomic) int16_t position;
@property (nonatomic, copy) NSString * _Nullable rating;
@property (nonatomic, copy) NSDate * _Nullable scheduledAt;
@property (nonatomic, copy) NSString * _Nullable secondLineAddress;
@property (nonatomic, strong) NSNumber * _Nullable showHasToLeaveByAlert;
@property (nonatomic, strong) NSNumber * _Nullable silent;
@property (nonatomic, copy) NSDate * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable zipcode;
@property (nonatomic, strong) NSSet * _Nullable contacts;
@property (nonatomic, strong) GGCustomer * _Nullable customer;
@property (nonatomic, strong) NSSet * _Nullable extraCustomers;
@property (nonatomic, strong) GGTask * _Nullable task;
@end


SWIFT_CLASS_NAMED("KeyValueEntity")
@interface KeyValueEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface KeyValueEntity (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


@interface KeyValueEntity (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable domain;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSData * _Nullable value;
@end


SWIFT_PROTOCOL("_TtP15BringgDriverSDK25LogReportsManagerProtocol_")
@protocol LogReportsManagerProtocol
- (void)sendLogsToServerWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_PROTOCOL("_TtP15BringgDriverSDK14LoggerProtocol_")
@protocol LoggerProtocol
- (void)logDebug:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSUInteger)line;
- (void)logInfo:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSUInteger)line;
- (void)logWarn:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSUInteger)line;
- (void)logError:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSUInteger)line;
@end

@class User;
@protocol UserEventsDelegate;
@class Merchant;

SWIFT_PROTOCOL("_TtP15BringgDriverSDK20LoginManagerProtocol_")
@protocol LoginManagerProtocol <NSObject>
@property (nonatomic, readonly, strong) User * _Nullable currentUser;
- (void)addDelegate:(id <UserEventsDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <UserEventsDelegate> _Nonnull)delegate;
- (void)loginWithEmail:(NSString * _Nonnull)email password:(NSString * _Nonnull)password merchantID:(NSNumber * _Nullable)merchantID completion:(void (^ _Nonnull)(NSArray<Merchant *> * _Nullable, NSError * _Nullable))completion;
- (void)requestVerificationCodeForPhone:(NSString * _Nonnull)phone completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)loginWithVerificationCode:(NSString * _Nonnull)code phone:(NSString * _Nonnull)phone merchantID:(NSNumber * _Nullable)merchantID completion:(void (^ _Nonnull)(NSArray<Merchant *> * _Nullable, NSError * _Nullable))completion;
- (void)loginWithQRCode:(NSString * _Nonnull)code completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)logoutWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)recoverPasswordForEmail:(NSString * _Nonnull)email completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC15BringgDriverSDK12LoginManager")
@interface LoginManager : NSObject <LoginManagerProtocol>
@property (nonatomic, readonly, strong) User * _Nullable currentUser;
- (void)addDelegate:(id <UserEventsDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <UserEventsDelegate> _Nonnull)delegate;
- (void)loginWithEmail:(NSString * _Nonnull)email password:(NSString * _Nonnull)password merchantID:(NSNumber * _Nullable)merchantID completion:(void (^ _Nonnull)(NSArray<Merchant *> * _Nullable, NSError * _Nullable))completion;
- (void)loginWithVerificationCode:(NSString * _Nonnull)code phone:(NSString * _Nonnull)phone merchantID:(NSNumber * _Nullable)merchantID completion:(void (^ _Nonnull)(NSArray<Merchant *> * _Nullable, NSError * _Nullable))completion;
- (void)loginWithQRCode:(NSString * _Nonnull)code completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)recoverPasswordForEmail:(NSString * _Nonnull)email completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)requestVerificationCodeForPhone:(NSString * _Nonnull)phone completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)logoutWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum MerchantType : NSInteger;

SWIFT_CLASS("_TtC15BringgDriverSDK8Merchant")
@interface Merchant : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) enum MerchantType type;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MerchantType) {
  MerchantTypeUnknown = -1,
  MerchantTypeProduction = 0,
  MerchantTypeStaging = 1,
};














SWIFT_CLASS("_TtC15BringgDriverSDK4Note")
@interface Note : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, NoteType) {
  NoteTypeTask = 0,
};


SWIFT_CLASS_NAMED("PersistentHTTPQueuedOperation")
@interface PersistentHTTPQueuedOperation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface PersistentHTTPQueuedOperation (SWIFT_EXTENSION(BringgDriverSDK)) <CoreDataModelable>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull entityName;)
+ (NSString * _Nonnull)entityName SWIFT_WARN_UNUSED_RESULT;
@end


@interface PersistentHTTPQueuedOperation (SWIFT_EXTENSION(BringgDriverSDK))
@property (nonatomic, copy) NSString * _Nullable endpoint;
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable operationId;
@property (nonatomic, copy) NSData * _Nullable parametersData;
@property (nonatomic, copy) NSDate * _Nullable requestTime;
@property (nonatomic, copy) NSString * _Nullable tag;
@end

typedef SWIFT_ENUM(NSInteger, ServerLoginResponseType) {
  ServerLoginResponseTypeUnknown = 0,
  ServerLoginResponseTypeUser = 1,
  ServerLoginResponseTypeMerchantsList = 2,
};


SWIFT_CLASS("_TtC15BringgDriverSDK5Shift")
@interface Shift : NSObject
@property (nonatomic, readonly) NSInteger shiftId;
@property (nonatomic, readonly, copy) NSDate * _Nonnull startDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable endDate;
- (nonnull instancetype)initWithId:(NSInteger)id startShift:(NSDate * _Nonnull)startShift endShift:(NSDate * _Nullable)endShift OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP15BringgDriverSDK18UserEventsDelegate_")
@protocol UserEventsDelegate
- (void)userDidLogin;
- (void)userDidLogout;
@end

@protocol ShiftManagerDelegate;
enum StartShiftErrorType : NSInteger;

SWIFT_PROTOCOL("_TtP15BringgDriverSDK20ShiftManagerProtocol_")
@protocol ShiftManagerProtocol
@property (nonatomic, readonly, strong) Shift * _Nullable currentShift;
- (void)addDelegate:(id <ShiftManagerDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <ShiftManagerDelegate> _Nonnull)delegate;
- (void)startShiftWithCompletion:(void (^ _Nonnull)(NSError * _Nullable, enum StartShiftErrorType))completion;
- (void)forceStartShiftWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)endShift;
@end


SWIFT_CLASS("_TtC15BringgDriverSDK12ShiftManager")
@interface ShiftManager : NSObject <ShiftManagerProtocol, UserEventsDelegate>
@property (nonatomic, readonly, strong) Shift * _Nullable currentShift;
- (void)addDelegate:(id <ShiftManagerDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <ShiftManagerDelegate> _Nonnull)delegate;
- (void)startShiftWithCompletion:(void (^ _Nonnull)(NSError * _Nullable, enum StartShiftErrorType))completion;
- (void)forceStartShiftWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)endShift;
- (void)userDidLogin;
- (void)userDidLogout;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_PROTOCOL("_TtP15BringgDriverSDK20ShiftManagerDelegate_")
@protocol ShiftManagerDelegate
- (void)shiftStarted;
- (void)shiftEnded;
@end






typedef SWIFT_ENUM(NSInteger, StartShiftErrorType) {
  StartShiftErrorTypeNone = 0,
  StartShiftErrorTypeAlreadyExists = 1,
  StartShiftErrorTypeAlreadyExistsOnDifferentDevice = 2,
  StartShiftErrorTypeNotAllowedDueToDistanceFromHome = 3,
  StartShiftErrorTypeNotAllowedDueToScheduleTimeOfDay = 4,
  StartShiftErrorTypeNotAllowedDueToDistanceFromScheduleHomeAndTimeOfDay = 5,
};


SWIFT_CLASS("_TtC15BringgDriverSDK4Task")
@interface Task : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15BringgDriverSDK13TaskInventory")
@interface TaskInventory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TaskStatus) {
  TaskStatusInvalid = -1,
  TaskStatusFree = 0,
  TaskStatusAssigned = 1,
  TaskStatusOnTheWay = 2,
  TaskStatusCheckedIn = 3,
  TaskStatusCheckedOut = 4,
  TaskStatusAccepted = 6,
  TaskStatusCancelled = 7,
  TaskStatusRejected = 8,
};


SWIFT_PROTOCOL("_TtP15BringgDriverSDK19TasksEventsDelegate_")
@protocol TasksEventsDelegate
- (void)tasksEventsProviderDidRefreshTaskList:(id <TasksManagerProtocol> _Nonnull)taskStateProvider;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didAddNewTask:(NSNumber * _Nonnull)taskId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didUpdateTask:(NSNumber * _Nonnull)taskId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didAddWaypoint:(NSNumber * _Nonnull)waypointId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didAddNote:(NSNumber * _Nonnull)noteId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didUpdateWaypoint:(NSNumber * _Nonnull)waypointId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didCompleteTask:(NSNumber * _Nonnull)taskId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didRemoveTask:(NSNumber * _Nonnull)taskId;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didMassRemoveTasks:(NSArray<NSNumber *> * _Nonnull)taskIds;
- (void)tasksEventsProvider:(id <TasksManagerProtocol> _Nonnull)tasksEventsProvider didRemoveWaypoint:(NSNumber * _Nonnull)waypointId;
@end


SWIFT_PROTOCOL("_TtP15BringgDriverSDK20TasksManagerProtocol_")
@protocol TasksManagerProtocol
- (void)addDelegate:(id <TasksEventsDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <TasksEventsDelegate> _Nonnull)delegate;
- (void)getTasksWithCompletion:(SWIFT_NOESCAPE void (^ _Nonnull)(NSArray<Task *> * _Nonnull, NSDate * _Nullable))completion;
- (void)refreshTasksWithCompletion:(void (^ _Nonnull)(NSArray<Task *> * _Nullable, NSError * _Nullable))completion;
- (void)getTaskWith:(NSInteger)taskId completion:(SWIFT_NOESCAPE void (^ _Nonnull)(Task * _Nullable))completion;
- (void)startTaskWith:(NSInteger)taskId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)arriveAtWaypointWith:(NSInteger)waypointId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)leaveWaypointWith:(NSInteger)waypointId completion:(void (^ _Nonnull)(NSNumber * _Nullable, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC15BringgDriverSDK4User")
@interface User : NSObject
@property (nonatomic, readonly, strong) NSNumber * _Nonnull userId;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly, copy) NSString * _Nullable profileImage;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) BOOL isHome;
@property (nonatomic, readonly) BOOL isDebug;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC15BringgDriverSDK8Waypoint")
@interface Waypoint : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, WaypointStatus) {
  WaypointStatusInvalid = 0,
  WaypointStatusPending = 1,
  WaypointStatusStarted = 2,
  WaypointStatusCheckedIn = 3,
  WaypointStatusDone = 4,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
