opt_in_rules:
  - force_unwrapping
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - array_init
  - explicit_init
  - first_where
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - fallthrough
  - switch_case_on_newline

disabled_rules:
  - todo
  - redundant_optional_initialization
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - nesting
  - multiline_arguments
  - redundant_string_enum_value
  - switch_case_on_newline

excluded:
  - Classes/DataLayer/KeychainAccess
  - Classes/Logger/LogContextKeysAndValues+KeyValue.swift # This is a generated file that might have trailing_whitespace issues

array_init: error

class_delegate_protocol: error

closure_parameter_position: error

closure_end_indentation: error

closure_spacing: error

colon:
  severity: error

comma: error

cyclomatic_complexity:
  warning: 50
  error: 50

empty_parameters: error

empty_parentheses_with_trailing_closure: error

explicit_init: error

fallthrough: error

type_name:
  max_length:
    error: 60
    warning: 60

file_length:
  warning: 1500
  error: 1500

first_where: error

force_unwrapping: error

function_body_length:
  warning: 50
  error: 50

function_parameter_count:
  warning: 9
  error: 9

identifier_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 100
    error: 100
  excluded:
    - id
    - URL
    - row
    - tag
    - key
    - sdk
    - app
    - url
    - lhs
    - rhs
    - rc
    - gps
    - env
    - lat
    - lng
    - now
    - on
    - off
    - eta
    - all
    - log
    - low
    - int
    - any
    - a
    - b
    - rt
    - t
    - ios
    - etl
    - ago
    - to
    - run

implicit_getter: error

implicitly_unwrapped_optional:
  severity: error

legacy_constant: error

line_length:
  warning: 230
  error: 230
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

trailing_whitespace:
  ignores_empty_lines: true
  severity: error

large_tuple: 
  error: 4
  warning: 4

literal_expression_end_indentation: error

mark: error

multiline_parameters: error

number_separator:
  severity: error
  minimum_length: 5

opening_brace: error

operator_usage_whitespace: error

overridden_super_call:
  severity: error

private_over_fileprivate:
  severity: error

protocol_property_accessors_order: error

redundant_discardable_let: error

redundant_void_return:
  severity: error

return_arrow_whitespace: error

sorted_first_last:
  severity: error

sorted_imports:
  severity: error

statement_position:
  severity: error

switch_case_alignment:
  severity: error

switch_case_on_newline: error

syntactic_sugar: error

trailing_comma:
  severity: error

trailing_newline: error

trailing_semicolon: error

unneeded_break_in_switch: error

unneeded_parentheses_in_closure_argument: error

unused_closure_parameter: error

unused_optional_binding:
  severity: error

vertical_parameter_alignment: error

vertical_parameter_alignment_on_call: error

vertical_whitespace:
  severity: error

void_return: error

weak_delegate: error

xctfail_message: error


private_unit_test:
  severity: error

type_body_length:
  warning: 1000
  error: 1000
