opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - comma
  - trailing_whitespace
  - literal_expression_end_indentation
  - mark
  - multiple_closures_with_trailing_closure
  - opening_brace
  - operator_usage_whitespace
  - return_arrow_whitespace
  - switch_case_alignment
  - switch_case_on_newline
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - sorted_imports

disabled_rules:
  - for_where
  - todo
  - line_length
  - identifier_name
  - large_tuple
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - type_body_length
  - switch_case_on_newline
  - number_separator
  - redundant_optional_initialization

excluded:
  - Pods
  - Classes/DataLayer/KeychainAccess
  - Classes/Logger/LogContextKeysAndValues+KeyValue.swift # This is a generated file that might have trailing_whitespace issues

closure_end_indentation: error

closure_spacing: error

colon:
  severity: error

comma: error

trailing_whitespace:
  ignores_empty_lines: true
  severity: error

literal_expression_end_indentation: error

mark: error

multiple_closures_with_trailing_closure: error

opening_brace: error

operator_usage_whitespace: error

return_arrow_whitespace: error

switch_case_alignment: error

switch_case_on_newline: error

trailing_comma:
  severity: error

trailing_newline: error

trailing_semicolon: error

vertical_parameter_alignment: error

vertical_parameter_alignment_on_call: error

vertical_whitespace:
  severity: error
