default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Description of what the lane does"
  lane :build_simulator do
    match(app_identifier: ["com.bringg.driverSDK.example"], type: "development", readonly: true)
    xcodebuild(
      workspace: 'BringgDriverSDK.xcworkspace',
      scheme: 'BringgDriverSDKExample',
      xcargs: "-configuration Debug -sdk 'iphonesimulator13.5' -destination 'generic/platform=iOS Simulator'"
    )    
  end
  lane :build_appstore do
    match(app_identifier: ["com.bringg.driverSDK.example"], type: "appstore", readonly: true)
    gym(
      configuration: "Release",
      export_method: "app-store",      
      output_directory: "build/appstore",
      output_name: "Bringg.ipa"
    )    
  end
end
