use_frameworks!
platform :ios, '11.0'

target 'BringgActiveCustomerSDKExample' do
  pod 'BringgDriverSDK', :path => '../'

  # These pods are used for the example app. You do not have to add them to your podfile
  pod 'CocoaLumberjack/Swift', '3.6.0'
  pod 'SnapKit'

  # All dependencies of the BringgDriverSDK needs to be built with the 'BUILD_LIBRARY_FOR_DISTRIBUTION' configuration set to 'YES'
  BringgDriverSDKDependencies = [
    'Socket.IO-Client-Swift',
    'Starscream',
    'libPhoneNumber-iOS',
    'GzipSwift',
    'Alamofire',
    'XCGLogger',
    'RealmSwift',
    'ObjcExceptionBridging',
    'Kingfisher',
    'KeychainAccess',
    'DeviceKit'
    ]
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if BringgDriverSDKDependencies.include? target.name
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end
